refactor!: Turn NonBlockingSocket into trait to allow alternate socket types
gschup/ggrs pull request #20
Opened 2021-09-02 11:24 UTC by johanhelsing

The session are now generic over the underlying socket type and is
passed an existing socket instead of creating one itself.

Some types had to be made public to make this work, for instance
UdpMessage is now a public (opaque-ish) type, implementors of the socket
trait should just serialize/deserialize it and pass it on to the
underlying socket.

2021-09-02 12:59 UTC, johanhelsing commented
So I hid the trait from the public API again... I guess it remains to be seen whether we can implement the webrtc transport within this crate or whether we want to have it in a separate crate

2021-09-02 13:02 UTC, johanhelsing commented
The good news is that I think this change is now non-breaking :)

2021-09-02 17:18 UTC, gschup requested changes
Great work refactoring the NonBlockingSocket into a trait object to allow for other sockets in the future! Here a few minor caveats I would like to be changed or checked before we merge this.

naming conventions:
- since the trait is called NonBlockingSocket, the file should be called non_blocking_socket.rs instead of nonblocking_socket.rs. Please rename the file and the module to fit naming conventions.

module structure: 
- there is both a file nonblocking_socket.rs (containing the trait def) and a module nonblocking_socket.rs (containing the currently only implementation of that trait). I would prefer for the trait definition to be moved into that module to make the structure more orderly.

details:
- please check again the visibility of modules, so that we didn't unintendedly expose parts. (I usually do this by calling `cargo doc --open` and check for entries that stand out e.g. without documentation)
- please make sure that the examples run. Since currently written tests are limited, it is better to also run the example (two players and a spectator) to make sure everything works as expected

2021-09-02 18:48 UTC, johanhelsing commented
I think I'll have some time to clean it up on Saturday.

There were issues with bevy_ggrs, but they are easy to fix. The trait just need to be send and sync as well.

2021-09-06 15:52 UTC, ValorZard commented
@johanhelsing were you able to work on it this weekend?

2021-09-06 16:37 UTC, johanhelsing commented
@ValorZard Yes! Or to be technical, not really.

I went straight for the fun and hacked together a demo that connects two players and establishes a webrtc data connection. I then implemented the trait here for it and made a fork of the bevy box_game example that uses it.

It needs some serious cleaning up before it's ready to be used but I'll try share it somewhere soon.

I'll start with this PR, then do another PR for the p2p webrtc socket. We might want to consider having it in a separate repo, though.

2021-09-06 16:39 UTC, ValorZard commented
That's amazing! This means that we could have rollback netcode ON THE BROWSER! Not even ggpo allows you to do that! Keep up the good work!

2021-09-06 16:41 UTC, gschup commented
We even had a small real internet demo between Johan and me and it worked quite well already!

2021-09-06 18:02 UTC, johanhelsing commented
Ok, I fixed the remaining things and force-pushed in order to reduce noise in commit history.

- nonblocking_socket -> non_blocking_socket
- non_blocking_socket.rs -> mod.rs
- trait is now send + sync as well, so bevy_ggrs is happy
- tested box_game in ggrs and bevy_ggrs with two players and everything still works :)

2021-09-06 18:08 UTC, merged