feat: Allow 3rd party socket implementations
gschup/ggrs pull request #21
Opened 2021-09-06 18:07 UTC by johanhelsing

2021-09-06 18:10 UTC, johanhelsing commented
This is what I needed to for my webrtc poc to work.

We could go the other way around and turn my webrtc stuff into a crate, which ggrs could have an optional dependency on.

That way, when building ggrs for wasm, you would automatically get the webrtc implementation (which would just be a thin wrapper around said hypothetical crate).

2021-09-06 18:16 UTC, johanhelsing commented
rebased after #20 was merged (so it's easier to read the diff)

2021-09-06 19:04 UTC, gschup requested changes
The addition of the "start with socket" fn seems very nice and straightforward, but I agree with your Todo comment that the trait object should be a generic, if possible. 

If you have the time, it would be nice to have a similar function for the P2PSpectatorSession, as well. If not, I'll add it later.

2021-09-07 10:28 UTC, johanhelsing commented
Added spectator version, made it take an impl NonBlockingSocket instead, and added docs :)

2021-09-07 11:00 UTC, gschup approved these changes

2021-09-07 11:06 UTC, merged